import { test, expect } from "@playwright/test";

test("escalation CRUD is separate from read-only coordination policies", async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem("crisis-policies-v1", JSON.stringify([{id:"D1",title:"Old editable doctrine"}])));
  await page.goto("/policies");
  await expect(page).toHaveURL(/\/escalation-policies$/);
  await expect(page.getByRole("heading", {name:"Políticas de escalado",exact:true})).toBeVisible();
  await expect(page.getByText("Old editable doctrine")).toHaveCount(0);
  await page.getByRole("button", {name:"Nueva política",exact:true}).click();
  const editor = page.getByRole("dialog");
  await editor.getByLabel("Identificador", {exact:true}).fill("ESC-QA");
  await editor.getByLabel("Título", {exact:true}).fill("Confirmación humana");
  await editor.getByLabel("Situación que requiere escalado").selectOption("rejected");
  await editor.getByLabel("Prioridad de la alerta").selectOption("critical");
  await editor.getByLabel("Cuándo debe escalar la IA").fill("Pedir al operador que revise las órdenes rechazadas.");
  await editor.getByRole("button", {name:"Guardar política"}).click();
  await page.reload();
  await expect(page.locator("#ESC-QA")).toContainText("Confirmación humana");
  await expect(page.locator("#ESC-QA")).toContainText("Crítica");
  await page.getByRole("button", {name:"Editar política ESC-QA",exact:true}).click();
  await editor.getByLabel("Título", {exact:true}).fill("Confirmación actualizada");
  await editor.getByRole("button", {name:"Guardar política"}).click();
  await expect(page.locator("#ESC-QA")).toContainText("Confirmación actualizada");
  await page.getByLabel("Modo de búsqueda").selectOption("text");
  await page.getByLabel("Buscar políticas", {exact:true}).fill("ESC-QA");
  await page.getByRole("button", {name:"Buscar",exact:true}).click();
  await expect(page.locator(".policies-layout article section")).toHaveCount(1);
  await page.getByRole("button", {name:"Editar política ESC-QA",exact:true}).click();
  await editor.getByRole("button", {name:"Eliminar política",exact:true}).click();
  await editor.getByRole("button", {name:"Confirmar eliminación"}).click();
  await page.goto("/escalation-policies#ESC-QA");
  await expect(page.locator("#ESC-QA")).toContainText("fue eliminada");
  await page.goto("/policies#D1");
  await expect(page).toHaveURL(/\/coordination-policies#D1$/);
  await expect(page.getByRole("heading", {name:"Políticas de coordinación",exact:true})).toBeVisible();
  await expect(page.getByText("Referencia D1", {exact:true})).toBeVisible();
  await expect(page.getByRole("button")).toHaveCount(0);
  await expect(page.getByText("Old editable doctrine")).toHaveCount(0);
});
