import { test, expect } from "@playwright/test";
import { serve } from "./support/engineRun";
import { ticketGraph, ticketRun } from "./support/ticketRun";
import { interventionGraph, interventionRun } from "./support/interventionRun";

test("operations scopes cases by sector and queue, opens evidence and preserves the way back", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));
  await serve(page, [ticketRun()]);
  await page.route("**/api/graph/ticket-test", (route) => route.fulfill({ json: ticketGraph }));
  await page.goto("/");
  await expect(page.getByRole("button", { name: "Operaciones", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByLabel("Navegar por el historial", { exact: true })).toHaveValue("5");
  await page.getByLabel("Navegar por el historial", { exact: true }).fill("3");
  await expect(page.getByTestId("ops-open")).toHaveText("5");
  await page.getByRole("button", { name: "Abrir sector Norte", exact: true }).click();
  await expect(page.locator(".ops-map-breadcrumb")).toContainText("Norte");
  await page.getByRole("button", { name: "Ver incidencias", exact: true }).click();
  await page.getByRole("button", { name: /^Abrir incidencia C1:/ }).click();
  const detail = page.getByRole("complementary", { name: "Detalle de incidencia" });
  await expect(detail).toContainText("A1 es la ambulancia disponible más cercana");
  await expect(page.locator(".ticket-scope")).toContainText("Norte");
  await page.getByRole("button", { name: "Operaciones", exact: true }).click();
  await expect(page.getByRole("button", { name: "Abrir sector Norte", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Cerrar sector", exact: true }).click();
  await page.getByLabel("Navegar por el historial", { exact: true }).fill("0");
  await expect(page.getByTestId("ops-open")).toHaveText("0");
  await expect(page.getByTestId("ops-calls")).toHaveText("0");
  expect(errors).toEqual([]);
});

test("scale view keeps thousands of cases navigable with bounded rows, search, map and mobile layout", async ({ page }) => {
  const errors: string[] = [], requested: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));
  page.on("request", (r) => requested.push(r.url()));
  await page.goto("/?escala=1");
  await expect(page.locator(".app-tabs button")).toHaveText(["Operaciones", "Incidencias"]);
  await expect(page.getByTestId("ops-calls")).toHaveText("12.000");
  await expect(page.getByTestId("ops-open")).toHaveText("1.866");
  await expect(page.locator(".ops-map-marker")).toHaveCount(6);
  await expect(page.locator(".ops-map-marker").first()).toBeInViewport();
  expect((await page.locator(".ops-map-canvas").boundingBox())?.height).toBeGreaterThan(200);
  await expect(page.locator(".ops-map-canvas")).toHaveAttribute("data-rendered", "true");
  await page.screenshot({ path: "test-results/operations-desktop.png", fullPage: true });
  await page.getByRole("button", { name: /Incidencias abiertas/ }).first().click();
  await expect(page.locator(".tickets-table tbody tr")).toHaveCount(50);
  const first = await page.locator(".tickets-table tbody tr").first().getAttribute("data-ticket");
  await page.getByLabel("Página siguiente de incidencias").click();
  await expect(page.locator(".tickets-table tbody tr").first()).not.toHaveAttribute("data-ticket", first!);
  await page.getByLabel("Buscar incidencias", { exact: true }).fill("DEMO-C2400");
  await expect(page.locator(".tickets-table tbody tr")).toHaveCount(1);
  await page.getByRole("button", { name: /^Abrir incidencia DEMO-C2400:/ }).click();
  await expect(page.getByRole("complementary", { name: "Detalle de incidencia" })).toContainText("DEMO-L11996");
  await page.getByRole("button", { name: "Ver sector en operaciones", exact: true }).click();
  await expect(page.getByRole("button", { name: "Operaciones", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator(".ops-sector[aria-pressed=true]")).toHaveCount(1);
  await expect(page.locator(".operational-map")).toHaveCount(0);
  expect(requested.some((url) => url.includes("/map/RunMap") || url.includes("/situation/SituationSidebar"))).toBe(false);
  await page.getByRole("button", { name: "Cerrar sector", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".ops-map-marker")).toHaveCount(6);
  await expect(page.locator(".ops-map-canvas")).toHaveAttribute("data-rendered", "true");
  await expect(page.getByRole("heading", { name: /Panorama operativo/ })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.screenshot({ path: "test-results/operations-mobile.png", fullPage: true });
  await page.getByLabel("Buscar sector").fill("suroeste");
  await expect(page.locator(".ops-sector")).toHaveCount(1);
  await page.getByRole("button", { name: "Abrir sector Suroeste", exact: true }).click();
  await expect(page.locator(".ops-map-breadcrumb")).toContainText("Suroeste");
  expect(errors).toEqual([]);
});

test("pending decisions never seize operations; the operator explicitly opens the decision room", async ({ page }) => {
  await serve(page, [interventionRun()]);
  await page.route("**/api/graph/ticket-test", (route) => route.fulfill({ json: interventionGraph }));
  await page.goto("/");
  const decisions = page.locator(".ops-decisions > button");
  await expect(decisions.first()).toBeVisible();
  await expect(page.getByRole("alertdialog")).toHaveCount(0);
  await expect(page.locator(".app-workspace")).not.toHaveAttribute("inert");
  await decisions.first().click();
  await expect(page.getByRole("alertdialog")).toBeVisible();
  await page.getByRole("button", { name: "Salir a investigar", exact: true }).click();
  await expect(page.getByRole("alertdialog")).toHaveCount(0);
  await expect(page.getByRole("heading", { name: /Panorama operativo/ })).toBeVisible();
});
